parameters:
  buildConfiguration: 'Release'

steps:

- task: ResharperCli@1
 inputs:
    SolutionOrProjectPath: '**/*.csproj'
    AdditionalArguments: '/disable-settings-layers:SolutionPersonal --properties:Configuration=${{parameters.buildConfiguration }}'
 env:
    MSBuildSDKsPath: '$(Agent.ToolsDirectory)/dncs/$(DotNet.Sdk.Version)/x64/sdk/$(DotNet.Sdk.Version)/Sdks'
- task: DotNetCoreCLI@2
  displayName: 'Build the project - ${{parameters.buildConfiguration }}'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.BuildConfiguration }}'
    zipAfterPublish: true