// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeLog.Models;

namespace TimeLog.Migrations
{
    [DbContext(typeof(TimeLogContext))]
    [Migration("20191125180225_add-invoice-support")]
    partial class addinvoicesupport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeLog.Models.ActivityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityTypeId");

                    b.Property<decimal>("ActualBilledDuration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Billable");

                    b.Property<decimal>("BillableRate")
                        .HasColumnType("money");

                    b.Property<int?>("ClientId");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("InvoiceItemId");

                    b.Property<string>("InvoiceStatement");

                    b.Property<int?>("LocationId");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("ProjectId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Tasks");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvoiceItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ActivityEntity");
                });

            modelBuilder.Entity("TimeLog.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("TimeLog.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("AddressLine3");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Region");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TimeLog.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DefaultBillableRate")
                        .HasColumnType("money");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TimeLog.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<string>("DisplayName");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TimeLog.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<int>("ClientId");

                    b.Property<int>("ContactId");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<int>("InvoiceNumber");

                    b.Property<string>("PrivateNote");

                    b.Property<string>("PublicNote");

                    b.Property<string>("PurchaseOrderNumber");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SubmitTypeId");

                    b.Property<DateTimeOffset>("SubmittedDate");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("TimeLog.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<DateTimeOffset>("DateEnd");

                    b.Property<string>("Description");

                    b.Property<int>("InvoiceId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<TimeSpan>("TotalDuration");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("TimeLog.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TimeLog.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DefaultActivityTypeId");

                    b.Property<decimal>("DefaultBillableRate")
                        .HasColumnType("money");

                    b.Property<int?>("DefaultClientId");

                    b.Property<int?>("DefaultLocationId");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DefaultActivityTypeId");

                    b.HasIndex("DefaultClientId");

                    b.HasIndex("DefaultLocationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeLog.Models.SubmitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SubmitTypes");
                });

            modelBuilder.Entity("TimeLog.ViewModels.Report", b =>
                {
                    b.Property<int>("ClientId");

                    b.Property<int>("ProjectId");

                    b.Property<bool>("Billable");

                    b.Property<decimal>("BillableAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClientId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("TimeLog.ViewModels.ReportDetailsByDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DayOfWeek");

                    b.Property<decimal>("Hrs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDay");

                    b.HasKey("Id");

                    b.ToTable("ReportDetailsByDay");
                });

            modelBuilder.Entity("TimeLog.ViewModels.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("DayOfWeek");

                    b.Property<decimal>("SumTotalDurationHours")
                        .HasColumnType("decimal(8,1)");

                    b.HasKey("Id");

                    b.ToTable("Summary");
                });

            modelBuilder.Entity("TimeLog.Models.ActivityEntity", b =>
                {
                    b.HasOne("TimeLog.Models.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TimeLog.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("TimeLog.Models.InvoiceItem")
                        .WithMany("Activities")
                        .HasForeignKey("InvoiceItemId");

                    b.HasOne("TimeLog.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("TimeLog.Models.ActivityEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TimeLog.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("TimeLog.Models.Contact", b =>
                {
                    b.HasOne("TimeLog.Models.Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TimeLog.Models.InvoiceItem", b =>
                {
                    b.HasOne("TimeLog.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TimeLog.Models.Project", b =>
                {
                    b.HasOne("TimeLog.Models.ActivityType", "DefaultActivityType")
                        .WithMany()
                        .HasForeignKey("DefaultActivityTypeId");

                    b.HasOne("TimeLog.Models.Client", "DefaultClient")
                        .WithMany()
                        .HasForeignKey("DefaultClientId");

                    b.HasOne("TimeLog.Models.Location", "DefaultLocation")
                        .WithMany()
                        .HasForeignKey("DefaultLocationId");
                });

            modelBuilder.Entity("TimeLog.ViewModels.Report", b =>
                {
                    b.HasOne("TimeLog.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TimeLog.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
